
languageCode = "en-us"
title = "Andrea Ciceri"
theme = "XMin"

relativeURLs = true

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 1
[[menu.main]]
    name = "Archive"
    url = "index.html"
    weight = 2
[[menu.main]]
    name = "Feed"
    url = "index.xml"

[params]
    footer = "[Andrea Ciceri](http://www.andreaciceri.altervista.org)"
