[build]
  base = "."
  publish = "blog/_website/"
  command = "cd blog/ && ablog build"

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
  
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
  minify = true
[build.processing.images]
  compress = true